/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemonstracaoRouteImport } from './routes/demonstracao'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBalancoAnualRouteImport } from './routes/_authenticated/balanco-anual'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedCompromissosRouteImport } from './routes/_authenticated/compromissos'
import { Route as AuthenticatedComprovantesRouteImport } from './routes/_authenticated/comprovantes'
import { Route as AuthenticatedConsultorRouteImport } from './routes/_authenticated/consultor'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedFechamentoRouteImport } from './routes/_authenticated/fechamento'
import { Route as AuthenticatedGasRouteImport } from './routes/_authenticated/gas'
import { Route as AuthenticatedKidsAuditoriaRouteImport } from './routes/_authenticated/kids-auditoria'
import { Route as AuthenticatedLancamentosRouteImport } from './routes/_authenticated/lancamentos'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedOrcamentosRouteImport } from './routes/_authenticated/orcamentos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedReceitasRouteImport } from './routes/_authenticated/receitas'
import { Route as AuthenticatedReconciliacaoRouteImport } from './routes/_authenticated/reconciliacao'
import { Route as AuthenticatedRecorrenciaRouteImport } from './routes/_authenticated/recorrencia'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedVeiculosRouteImport } from './routes/_authenticated/veiculos'
import { Route as AuthenticatedVeiculosAuditoriaRouteImport } from './routes/_authenticated/veiculos-auditoria'
import { Route as AuthenticatedVeiculosConfiguracoesRouteImport } from './routes/_authenticated/veiculos-configuracoes'
import { Route as AuthenticatedVeiculosRelatorioRouteImport } from './routes/_authenticated/veiculos-relatorio'
import { Route as CompartilhadoTokenRouteImport } from './routes/compartilhado.$token'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as ApiPublicMercadopagoRouteImport } from './routes/api/public/mercadopago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoRoute = DemonstracaoRouteImport.update({
  id: '/demonstracao',
  path: '/demonstracao',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBalancoAnualRoute =
  AuthenticatedBalancoAnualRouteImport.update({
    id: '/balanco-anual',
    path: '/balanco-anual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompromissosRoute =
  AuthenticatedCompromissosRouteImport.update({
    id: '/compromissos',
    path: '/compromissos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprovantesRoute =
  AuthenticatedComprovantesRouteImport.update({
    id: '/comprovantes',
    path: '/comprovantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultorRoute = AuthenticatedConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFechamentoRoute = AuthenticatedFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGasRoute = AuthenticatedGasRouteImport.update({
  id: '/gas',
  path: '/gas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKidsAuditoriaRoute =
  AuthenticatedKidsAuditoriaRouteImport.update({
    id: '/kids-auditoria',
    path: '/kids-auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLancamentosRoute =
  AuthenticatedLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosRoute = AuthenticatedOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceitasRoute = AuthenticatedReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReconciliacaoRoute =
  AuthenticatedReconciliacaoRouteImport.update({
    id: '/reconciliacao',
    path: '/reconciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecorrenciaRoute =
  AuthenticatedRecorrenciaRouteImport.update({
    id: '/recorrencia',
    path: '/recorrencia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculosRoute = AuthenticatedVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeiculosAuditoriaRoute =
  AuthenticatedVeiculosAuditoriaRouteImport.update({
    id: '/veiculos-auditoria',
    path: '/veiculos-auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVeiculosConfiguracoesRoute =
  AuthenticatedVeiculosConfiguracoesRouteImport.update({
    id: '/veiculos-configuracoes',
    path: '/veiculos-configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVeiculosRelatorioRoute =
  AuthenticatedVeiculosRelatorioRouteImport.update({
    id: '/veiculos-relatorio',
    path: '/veiculos-relatorio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CompartilhadoTokenRoute = CompartilhadoTokenRouteImport.update({
  id: '/compartilhado/$token',
  path: '/compartilhado/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoRoute = ApiPublicMercadopagoRouteImport.update({
  id: '/api/public/mercadopago',
  path: '/api/public/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/balanco-anual': typeof AuthenticatedBalancoAnualRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/compromissos': typeof AuthenticatedCompromissosRoute
  '/comprovantes': typeof AuthenticatedComprovantesRoute
  '/consultor': typeof AuthenticatedConsultorRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/gas': typeof AuthenticatedGasRoute
  '/kids-auditoria': typeof AuthenticatedKidsAuditoriaRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/reconciliacao': typeof AuthenticatedReconciliacaoRoute
  '/recorrencia': typeof AuthenticatedRecorrenciaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/veiculos-auditoria': typeof AuthenticatedVeiculosAuditoriaRoute
  '/veiculos-configuracoes': typeof AuthenticatedVeiculosConfiguracoesRoute
  '/veiculos-relatorio': typeof AuthenticatedVeiculosRelatorioRoute
  '/compartilhado/$token': typeof CompartilhadoTokenRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/balanco-anual': typeof AuthenticatedBalancoAnualRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/compromissos': typeof AuthenticatedCompromissosRoute
  '/comprovantes': typeof AuthenticatedComprovantesRoute
  '/consultor': typeof AuthenticatedConsultorRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/fechamento': typeof AuthenticatedFechamentoRoute
  '/gas': typeof AuthenticatedGasRoute
  '/kids-auditoria': typeof AuthenticatedKidsAuditoriaRoute
  '/lancamentos': typeof AuthenticatedLancamentosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/reconciliacao': typeof AuthenticatedReconciliacaoRoute
  '/recorrencia': typeof AuthenticatedRecorrenciaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/veiculos': typeof AuthenticatedVeiculosRoute
  '/veiculos-auditoria': typeof AuthenticatedVeiculosAuditoriaRoute
  '/veiculos-configuracoes': typeof AuthenticatedVeiculosConfiguracoesRoute
  '/veiculos-relatorio': typeof AuthenticatedVeiculosRelatorioRoute
  '/compartilhado/$token': typeof CompartilhadoTokenRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demonstracao': typeof DemonstracaoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/balanco-anual': typeof AuthenticatedBalancoAnualRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/compromissos': typeof AuthenticatedCompromissosRoute
  '/_authenticated/comprovantes': typeof AuthenticatedComprovantesRoute
  '/_authenticated/consultor': typeof AuthenticatedConsultorRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/fechamento': typeof AuthenticatedFechamentoRoute
  '/_authenticated/gas': typeof AuthenticatedGasRoute
  '/_authenticated/kids-auditoria': typeof AuthenticatedKidsAuditoriaRoute
  '/_authenticated/lancamentos': typeof AuthenticatedLancamentosRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/orcamentos': typeof AuthenticatedOrcamentosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/receitas': typeof AuthenticatedReceitasRoute
  '/_authenticated/reconciliacao': typeof AuthenticatedReconciliacaoRoute
  '/_authenticated/recorrencia': typeof AuthenticatedRecorrenciaRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/veiculos': typeof AuthenticatedVeiculosRoute
  '/_authenticated/veiculos-auditoria': typeof AuthenticatedVeiculosAuditoriaRoute
  '/_authenticated/veiculos-configuracoes': typeof AuthenticatedVeiculosConfiguracoesRoute
  '/_authenticated/veiculos-relatorio': typeof AuthenticatedVeiculosRelatorioRoute
  '/compartilhado/$token': typeof CompartilhadoTokenRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demonstracao'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/admin'
    | '/balanco-anual'
    | '/cadastros'
    | '/calendario'
    | '/categorias'
    | '/compromissos'
    | '/comprovantes'
    | '/consultor'
    | '/diario'
    | '/fechamento'
    | '/gas'
    | '/kids-auditoria'
    | '/lancamentos'
    | '/metas'
    | '/onboarding'
    | '/orcamentos'
    | '/painel'
    | '/perfil'
    | '/receitas'
    | '/reconciliacao'
    | '/recorrencia'
    | '/relatorios'
    | '/veiculos'
    | '/veiculos-auditoria'
    | '/veiculos-configuracoes'
    | '/veiculos-relatorio'
    | '/compartilhado/$token'
    | '/pedido/$id'
    | '/api/public/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demonstracao'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/admin'
    | '/balanco-anual'
    | '/cadastros'
    | '/calendario'
    | '/categorias'
    | '/compromissos'
    | '/comprovantes'
    | '/consultor'
    | '/diario'
    | '/fechamento'
    | '/gas'
    | '/kids-auditoria'
    | '/lancamentos'
    | '/metas'
    | '/onboarding'
    | '/orcamentos'
    | '/painel'
    | '/perfil'
    | '/receitas'
    | '/reconciliacao'
    | '/recorrencia'
    | '/relatorios'
    | '/veiculos'
    | '/veiculos-auditoria'
    | '/veiculos-configuracoes'
    | '/veiculos-relatorio'
    | '/compartilhado/$token'
    | '/pedido/$id'
    | '/api/public/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demonstracao'
    | '/privacidade'
    | '/redefinir-senha'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/balanco-anual'
    | '/_authenticated/cadastros'
    | '/_authenticated/calendario'
    | '/_authenticated/categorias'
    | '/_authenticated/compromissos'
    | '/_authenticated/comprovantes'
    | '/_authenticated/consultor'
    | '/_authenticated/diario'
    | '/_authenticated/fechamento'
    | '/_authenticated/gas'
    | '/_authenticated/kids-auditoria'
    | '/_authenticated/lancamentos'
    | '/_authenticated/metas'
    | '/_authenticated/onboarding'
    | '/_authenticated/orcamentos'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/_authenticated/receitas'
    | '/_authenticated/reconciliacao'
    | '/_authenticated/recorrencia'
    | '/_authenticated/relatorios'
    | '/_authenticated/veiculos'
    | '/_authenticated/veiculos-auditoria'
    | '/_authenticated/veiculos-configuracoes'
    | '/_authenticated/veiculos-relatorio'
    | '/compartilhado/$token'
    | '/pedido/$id'
    | '/api/public/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemonstracaoRoute: typeof DemonstracaoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosRoute: typeof TermosRoute
  CompartilhadoTokenRoute: typeof CompartilhadoTokenRoute
  PedidoIdRoute: typeof PedidoIdRoute
  ApiPublicMercadopagoRoute: typeof ApiPublicMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao': {
      id: '/demonstracao'
      path: '/demonstracao'
      fullPath: '/demonstracao'
      preLoaderRoute: typeof DemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/balanco-anual': {
      id: '/_authenticated/balanco-anual'
      path: '/balanco-anual'
      fullPath: '/balanco-anual'
      preLoaderRoute: typeof AuthenticatedBalancoAnualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compromissos': {
      id: '/_authenticated/compromissos'
      path: '/compromissos'
      fullPath: '/compromissos'
      preLoaderRoute: typeof AuthenticatedCompromissosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comprovantes': {
      id: '/_authenticated/comprovantes'
      path: '/comprovantes'
      fullPath: '/comprovantes'
      preLoaderRoute: typeof AuthenticatedComprovantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultor': {
      id: '/_authenticated/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof AuthenticatedConsultorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fechamento': {
      id: '/_authenticated/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof AuthenticatedFechamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gas': {
      id: '/_authenticated/gas'
      path: '/gas'
      fullPath: '/gas'
      preLoaderRoute: typeof AuthenticatedGasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kids-auditoria': {
      id: '/_authenticated/kids-auditoria'
      path: '/kids-auditoria'
      fullPath: '/kids-auditoria'
      preLoaderRoute: typeof AuthenticatedKidsAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lancamentos': {
      id: '/_authenticated/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AuthenticatedLancamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos': {
      id: '/_authenticated/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AuthenticatedOrcamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receitas': {
      id: '/_authenticated/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AuthenticatedReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliacao': {
      id: '/_authenticated/reconciliacao'
      path: '/reconciliacao'
      fullPath: '/reconciliacao'
      preLoaderRoute: typeof AuthenticatedReconciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recorrencia': {
      id: '/_authenticated/recorrencia'
      path: '/recorrencia'
      fullPath: '/recorrencia'
      preLoaderRoute: typeof AuthenticatedRecorrenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos': {
      id: '/_authenticated/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof AuthenticatedVeiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos-auditoria': {
      id: '/_authenticated/veiculos-auditoria'
      path: '/veiculos-auditoria'
      fullPath: '/veiculos-auditoria'
      preLoaderRoute: typeof AuthenticatedVeiculosAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos-configuracoes': {
      id: '/_authenticated/veiculos-configuracoes'
      path: '/veiculos-configuracoes'
      fullPath: '/veiculos-configuracoes'
      preLoaderRoute: typeof AuthenticatedVeiculosConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veiculos-relatorio': {
      id: '/_authenticated/veiculos-relatorio'
      path: '/veiculos-relatorio'
      fullPath: '/veiculos-relatorio'
      preLoaderRoute: typeof AuthenticatedVeiculosRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/compartilhado/$token': {
      id: '/compartilhado/$token'
      path: '/compartilhado/$token'
      fullPath: '/compartilhado/$token'
      preLoaderRoute: typeof CompartilhadoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago': {
      id: '/api/public/mercadopago'
      path: '/api/public/mercadopago'
      fullPath: '/api/public/mercadopago'
      preLoaderRoute: typeof ApiPublicMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBalancoAnualRoute: typeof AuthenticatedBalancoAnualRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedCompromissosRoute: typeof AuthenticatedCompromissosRoute
  AuthenticatedComprovantesRoute: typeof AuthenticatedComprovantesRoute
  AuthenticatedConsultorRoute: typeof AuthenticatedConsultorRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedFechamentoRoute: typeof AuthenticatedFechamentoRoute
  AuthenticatedGasRoute: typeof AuthenticatedGasRoute
  AuthenticatedKidsAuditoriaRoute: typeof AuthenticatedKidsAuditoriaRoute
  AuthenticatedLancamentosRoute: typeof AuthenticatedLancamentosRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrcamentosRoute: typeof AuthenticatedOrcamentosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedReceitasRoute: typeof AuthenticatedReceitasRoute
  AuthenticatedReconciliacaoRoute: typeof AuthenticatedReconciliacaoRoute
  AuthenticatedRecorrenciaRoute: typeof AuthenticatedRecorrenciaRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVeiculosRoute: typeof AuthenticatedVeiculosRoute
  AuthenticatedVeiculosAuditoriaRoute: typeof AuthenticatedVeiculosAuditoriaRoute
  AuthenticatedVeiculosConfiguracoesRoute: typeof AuthenticatedVeiculosConfiguracoesRoute
  AuthenticatedVeiculosRelatorioRoute: typeof AuthenticatedVeiculosRelatorioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBalancoAnualRoute: AuthenticatedBalancoAnualRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedCompromissosRoute: AuthenticatedCompromissosRoute,
  AuthenticatedComprovantesRoute: AuthenticatedComprovantesRoute,
  AuthenticatedConsultorRoute: AuthenticatedConsultorRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedFechamentoRoute: AuthenticatedFechamentoRoute,
  AuthenticatedGasRoute: AuthenticatedGasRoute,
  AuthenticatedKidsAuditoriaRoute: AuthenticatedKidsAuditoriaRoute,
  AuthenticatedLancamentosRoute: AuthenticatedLancamentosRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrcamentosRoute: AuthenticatedOrcamentosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedReceitasRoute: AuthenticatedReceitasRoute,
  AuthenticatedReconciliacaoRoute: AuthenticatedReconciliacaoRoute,
  AuthenticatedRecorrenciaRoute: AuthenticatedRecorrenciaRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVeiculosRoute: AuthenticatedVeiculosRoute,
  AuthenticatedVeiculosAuditoriaRoute: AuthenticatedVeiculosAuditoriaRoute,
  AuthenticatedVeiculosConfiguracoesRoute:
    AuthenticatedVeiculosConfiguracoesRoute,
  AuthenticatedVeiculosRelatorioRoute: AuthenticatedVeiculosRelatorioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemonstracaoRoute: DemonstracaoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosRoute: TermosRoute,
  CompartilhadoTokenRoute: CompartilhadoTokenRoute,
  PedidoIdRoute: PedidoIdRoute,
  ApiPublicMercadopagoRoute: ApiPublicMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
